apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-kiosk-beta
  labels:
    tier: frontend
    environment: beta
spec:
  selector:
    matchLabels:
      app: frontend-kiosk-beta
      tier: frontend
      environment: beta
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: frontend-kiosk-beta
        tier: frontend
        environment: beta
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: simplaq-beta-v3-4gb
      containers:
        - name: frontend
          image: registry.digitalocean.com/simplaq/k8s-simplaq-frontend-kiosk:beta
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            # beta config
            - configMapRef:
                name: frontend-kiosk-beta-config
